### Authorization
POST http://localhost:9080/signIn
Content-Type: application/json

{
  "email": "new@gmail.com",
  "password": "123"
}

### Registration
POST http://localhost:9080/blogUsers
Content-Type: application/json

{
  "login" : "new@gmail.com",
  "password": "123"
}
###